# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CVNo5TrMX2j53VM3Dx0bdNwzK8a7XC8K
"""

n = int(input("Digite o número de repetições para a sequência de Fibonacci: "))

a = 0
b = 1
count = 0

if n <= 0:
    print("Por favor, digite um número inteiro positivo.")
elif n == 1:
    print("Sequência de Fibonacci:")
    print(a)
else:
    print("Sequência de Fibonacci:")
    while count < n:
        print(a, end=" ")
        nth = a + b
        a = b
        b = nth
        count += 1